name: CI/CD

on:
  push:
    branches:
      - master
      - staging
      
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
      
    - name: Create env
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        DB_PASSWORD: ${{ secrets.APP_PASSWORD }}
        DB_CONNECTION: mongodb
        DB_PORT: 3306
        DB_DATABASE: Cluster0
        DB_USERNAME: root
        file_name: .env
        
    - name: Install Composer dependencies
      run: composer install --ignore-platform-reqs
    - name: Install NPM dependencies
      run: npm install
    - name: Compile assets for production
      run: npm run watch &
    - name: Generate Key
      run: php artisan key:generate

    
    - name: Migrate
      run: php artisan migrate
        
        
    - name: "Install ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: "Install DPL"
      run: gem install dpl

    - name: "Deploy to Heroku"
      run: dpl --provider=heroku --app=${{secrets.HEROKU_APP}} --api-key=${{secrets.HEROKU_API_KEY}} --skip_cleanup=true

